version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: example@email.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - 8080:80
    depends_on:
      - db
